import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		int boy = 0; 
		int girl = 0;
		int sum = 0;
		int counting = 0 ; 
		int F2 = 0;
		int F3 = 0;
		int F4 = 0;
		

		for (int j = 0 ; j < T ; j ++){
			boy = 0;
			girl =0;
			counting= 0;
			while ( boy == 0 || girl == 0 ){ 
				double chance = generator.nextDouble(); 
				if(chance > 0.5) {
					boy++;
					
				}
				else{
					girl++;
				}
				counting +=1 ;
				 
				}
			sum += counting;

				if( counting == 2 ){
				F2 ++ ; 
				}
				else if( counting == 3 ){
				F3 ++ ; 
				}
				else{
				F4 ++ ; 
				}
				counting = 0 ; 
				 ; 
			}	
		System.out.println();
		System.out.println((double)sum/T + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + F2);
		System.out.println("Number of families with 3 children: "  + F3 );
		System.out.println("Number of families with 4 or more children:" + F4);
		
		if (F2 == Math.max( Math.max(F2,F3),F4)){ System.out.println("The most common number of children is 2.");}
		if (F3 == Math.max( Math.max(F2,F3),F4)){ System.out.println("The most common number of children is 3." );} 
		else{ System.out.println("The most common number of children is 4 or more.");}

		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
